### ISSUE TITLE
matching.py

### ISSUE THREAD

**Issue by oyamad** [NlGG/matching#1]
28行目でエラーが出ます．
テストが通るように完成させましょう．

`have` というリストに `-1` を入れてますが，これはどういう意味？

@yoshimasaogawa 見てあげてください．

**Comment by ghost** [comment]
申し訳ございません、注意書きを加えるのを忘れておりました。mもfもunmatched=-1で単体テストを行いました。
unmatched=-1のもとではテスト通過の確認をとれております。

**Comment by oyamad** [comment]
ああなるほど．

スピードコンテストをやるときにデータの方をいちいち変えるのがたいへんなので，すみませんがソースの方を `mnum` と `fnum` に変えてもらえませんか．

`m_unmatched`, `f_unmatched` を

``` python
m_unmatched, f_unmatched = mnum, fnum
```

のように定義し，現状で `-1` として埋め込まれている部分を適切に `m_unmatched` と `f_unmatched` に変える．正しく返ればテストそのまま通るはずです．

**Comment by ghost** [comment]
かしこまりました。明日のゼミまでには2人で修正してテスト通過の確認をとっておきます。よろしくお願い致します。

**Comment by oyamad** [comment]
よくできました．
