### ISSUE TITLE
「受け入れ最大数」について

### ISSUE THREAD

**Issue by haru110jp** [NlGG/matching#2]
今少し考えてみてたのですが、ひとつ問題に気が付きました
resp_prefsの中に「こんなやつ取るくらいなら、まだ定員以下だけど拒否する」というような感じの選好が入ることがありうるので、（課題のデータ形式指定を見て考えてみてください）「形式上のcapacity」と「事実上のcapacity」が異なってくる可能性があります

単純な解決策としては、事前に形式上のと事実上のとどちらがbindingかをしらべて、本物のcapacityを定義してからマッチングを記述するか、逐一どちらとも大小比較するかだと思います
前者のがすっきりしそうだと思ってますが、どうでしょうか

**Comment by oyamad** [comment]
どう実装するかによりますが，`resp_matched` を初期化するときにすべて unmatched を表す数字を入れておいてやれば「形式上のcapacity」と「事実上のcapacity」が異なっても関係ない気がしますがどうでしょう．

(両者が異なるときに「形式上のcapacity」分まですべて探索するのは非効率，ということですか．それならその通りでしょうが，両者が異なるケースは重要でないケースなので，それのためにコードの readability を下げることもないと思いますが．)

**Comment by haru110jp** [comment]
不明瞭ですみません、後者の方の意味でした。先にbindingなcapacityを計算した方が余分な処理がなくて後がすっきりするような気がしたのですが、確かに読んでいてわかりにくくなりそうです
とりあえずシンプルに考えてみます、ありがとうございます
